### ISSUE TITLE
Audio engine crashes if sample buffers larger than 1024 are used (ASIO - Windows 10)

### ISSUE THREAD

**Issue by git-moss** [teotigraphix/Framework4Bitwig#86]
E.g. 2048. Tested with Steinberg UR824.

**Comment by vosc** [comment]
Which audio backend did you use? ASIO?

**Comment by git-moss** [comment]
Yes

**Comment by git-moss** [comment]
Still in Beta 7.

**Comment by vosc** [comment]
should be fixed in beta-8.

**Comment by git-moss** [comment]
Great! That was very annoying.

**Comment by git-moss** [comment]
Fixed.

**Comment by git-moss** [comment]
It's not fixed. It does no longer crash straight away but when you try to play something. Crash reports sent.

**Comment by git-moss** [comment]
Still crashing in Beta 8. 2 Crash reports sent.

**Comment by git-moss** [comment]
Still in 1.2.

**Comment by abique** [comment]
Hey moss, is that one fixed for you in the latest 1.3?

**Comment by git-moss** [comment]
No, still crashing in 1.3 RC1. I just sent a crash report.

**Comment by git-moss** [comment]
Still in 1.3 RC2.

**Comment by abique** [comment]
Sorry to ask again, is it still there?

**Comment by git-moss** [comment]
Yes, it is still in 1.3.1, could not check with the new RC1 yet. Was there a change? Can I give you some more information?

**Comment by abique** [comment]
If you know the sample type that could help :)

**Comment by git-moss** [comment]
What do you mean by Sample Type?

**Comment by abique** [comment]
If it is 24 bit depth little endian store inside a 32 bit integer (8 bits padding), or if it is just 24 bits without padding between samples.

Sample type == sample format.

**Comment by git-moss** [comment]
Ah ok, I am on a business trip and will look it up when I am back at home at the weekend.

**Comment by git-moss** [comment]
I tried with 44.1, 48 and 96 on 2048 samples. All crashed. 
But where can I see / set the bit depth? There is nothing in the driver.

**Comment by abique** [comment]
If you have linux, you can run alsa-info.sh (provided by alsa-utils).

On my computer this is the report file: http://www.alsa-project.org/db/?f=71b25c46175a00efda70559c050225f847af4f8f

**Comment by git-moss** [comment]
I don't have a Linux machine but I just setup an Ubuntu VM. I will try if it will run on the VM.

**Comment by git-moss** [comment]
When I connect the UR824 to the Linux VM Windows crashes.
Is there any way I can get you more info on Windows? Maybe Claes know how?

**Comment by git-moss** [comment]
@abique I sent you an email with more info.

**Comment by git-moss** [comment]
Still in 1.3.8 RC1

**Comment by git-moss** [comment]
Still in 1.3.8 RC 2.

**Comment by abique** [comment]
We could not figure what's happening with this issue. The next time you come to Berlin, please can you take your sound card with you? That would help us to reproduce the bug in a debugging environment.

Thank you very much.

**Comment by git-moss** [comment]
Will do.

**Comment by git-moss** [comment]
Fixed in 1.3.8 RC 4!
It is missing in the readme of RC4 that it is fixed.
